AllCops:
  Exclude:
    - test/**/*
    - tmp/**/*
  TargetRubyVersion: 2.7
  NewCops: enable
  SuggestExtensions: false

# Documentation:
#   Enabled: false

Gemspec/RequireMFA:
  Enabled: false

Layout/LineLength:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Layout/ExtraSpacing:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - '*.gemspec'
    - 'Rakefile'
    - '**/*.rake'
    - 'spec/**/*.rb'

Layout/SpaceAroundOperators:
  AllowForAlignment: true
